---
- hosts: all
  vars:
    - username: sammy
    - home: /home/sammy   
  tasks:
    - name: impresion de variables
      debug:
        msg: "Nombre usuario: {{ username }}, directorio principal: {{ home }}"
